resource "mongodbatlas_advanced_cluster" "this" {
  project_id   = var.project_id
  name         = var.cluster_name
  cluster_type = "REPLICASET"
  replication_specs = [
    {
      region_configs = [
        {
          provider_name = "AWS"
          region_name   = "US_WEST_1"
          priority      = 7
          electable_specs = {
            node_count    = 2
            instance_size = var.instance_size
          }
        }
      ]
    }
  ]
  advanced_configuration = {
    # comments in advanced_configuration are kept
    javascript_enabled = true
  }
  bi_connector_config = {
    # comments in bi_connector_config are kept
    enabled         = true
    read_preference = "secondary"
  }
  pinned_fcv = {
    # comments in pinned_fcv are kept
    expiration_date = var.fcv_date
  }

  # Generated by atlas-cli-plugin-terraform.
  # Please review the changes and confirm that references to this resource are updated.
}
