resource "mongodbatlas_advanced_cluster" "ar" {
  project_id   = var.project_id
  name         = "ar"
  cluster_type = "REPLICASET"
  replication_specs = [
    {
      region_configs = [
        {
          provider_name = "AWS"
          region_name   = "US_EAST_1"
          priority      = 7
          electable_specs = {
            node_count    = 3
            instance_size = "M10"
          }
          read_only_specs = {
            node_count    = 1
            instance_size = "M10"
          }
          analytics_specs = {
            node_count    = 2
            instance_size = "M10"
          }
        }
      ]
    }
  ]

  # Generated by atlas-cli-plugin-terraform.
  # Please review the changes and confirm that references to this resource are updated.
}

resource "mongodbatlas_advanced_cluster" "ar_not_electable" {
  project_id   = var.project_id
  name         = "ar"
  cluster_type = "REPLICASET"
  replication_specs = [
    {
      region_configs = [
        {
          provider_name = "AWS"
          region_name   = "US_EAST_1"
          priority      = 7
          read_only_specs = {
            node_count    = 1
            instance_size = "M10"
          }
          analytics_specs = {
            node_count    = 2
            instance_size = "M10"
          }
        }
      ]
    }
  ]

  # Generated by atlas-cli-plugin-terraform.
  # Please review the changes and confirm that references to this resource are updated.
}
