resource "mongodbatlas_advanced_cluster" "different_var_names" {
  project_id   = var.project_id
  name         = var.cluster_name
  cluster_type = var.cluster_type
  replication_specs = flatten([
    for spec in var.my_rep_specs : [
      for i in range(spec.my_shards) : {
        zone_name = spec.my_zone
        region_configs = flatten([
          # Regions must be sorted by priority in descending order.
          for priority in range(7, 0, -1) : [
            for region in spec.my_regions : {
              provider_name = var.provider_name
              region_name   = region.my_region_name
              priority      = region.prio
              electable_specs = region.my_electable_nodes == 0 ? null : {
                node_count    = region.my_electable_nodes
                instance_size = var.instance_size
              }
            } if priority == region.prio
          ]
        ])
      }
    ]
  ])

  # Generated by atlas-cli-plugin-terraform.
  # Please review the changes and confirm that references to this resource are updated.
}

resource "mongodbatlas_advanced_cluster" "different_var_names_no_zone_name" {
  project_id   = var.project_id
  name         = var.cluster_name
  cluster_type = var.cluster_type
  replication_specs = flatten([
    for spec in var.my_rep_specs : [
      for i in range(spec.my_shards) : {
        region_configs = flatten([
          # Regions must be sorted by priority in descending order.
          for priority in range(7, 0, -1) : [
            for region in spec.my_regions : {
              provider_name = var.provider_name
              region_name   = region.my_region_name
              priority      = region.prio
              electable_specs = region.my_electable_nodes == 0 ? null : {
                node_count    = region.my_electable_nodes
                instance_size = var.instance_size
              }
            } if priority == region.prio
          ]
        ])
      }
    ]
  ])

  # Generated by atlas-cli-plugin-terraform.
  # Please review the changes and confirm that references to this resource are updated.
}
