locals {
  replication_specs_list = [
    {
      zone_name   = "zone1"
      region_name = "US_EAST_1"
    },
    {
      zone_name   = "zone2"
      region_name = "US_WEST_2"
    }
  ]
}

resource "mongodbatlas_advanced_cluster" "one_config" {
  project_id = "123"
  name       = "cluster"
  replication_specs = flatten([
    for spec in local.replication_specs_list : [
      for i in range(2) : {
        zone_name = spec.zone_name
        region_configs = [
          {
            provider_name = "AWS"
            region_name   = spec.region_name
            priority      = 7
            electable_specs = {
              node_count    = 3
              instance_size = "M10"
              disk_size_gb  = 10
            }
            auto_scaling = {
              disk_gb_enabled = true
            }
          }
        ]
      }
    ]
  ])

  # Generated by atlas-cli-plugin-terraform.
  # Please review the changes and confirm that references to this resource are updated.
}

resource "mongodbatlas_advanced_cluster" "multiple_config" {
  project_id = "123"
  name       = "cluster"
  replication_specs = flatten([
    for spec in local.replication_specs_list : [
      for i in range(2) : {
        zone_name = spec.zone_name
        region_configs = [
          {
            provider_name = "AWS"
            region_name   = spec.region_name
            priority      = 7
            electable_specs = {
              node_count    = 2
              instance_size = "M10"
              disk_size_gb  = 10
            }
            auto_scaling = {
              disk_gb_enabled = true
            }
          },
          {
            provider_name = "AWS"
            region_name   = spec.region_name
            priority      = 6
            electable_specs = {
              node_count    = 1
              instance_size = "M10"
              disk_size_gb  = 10
            }
            read_only_specs = {
              node_count    = 4
              instance_size = "M10"
              disk_size_gb  = 10
            }
            auto_scaling = {
              disk_gb_enabled = true
            }
          }
        ]
      }
    ]
  ])

  # Generated by atlas-cli-plugin-terraform.
  # Please review the changes and confirm that references to this resource are updated.
}
