resource "mongodbatlas_advanced_cluster" "dynamic_regions_config" {
  project_id   = var.project_id
  name         = "cluster"
  cluster_type = "SHARDED"
  replication_specs = [
    for i in range(var.replication_specs.num_shards) : {
      region_configs = flatten([
        for priority in range(7, 0, -1) : [
          for region in var.replication_specs.regions_config : {
            provider_name = "AWS"
            region_name   = region.region_name
            priority      = region.priority
            electable_specs = region.electable_nodes > 0 ? {
              node_count    = region.electable_nodes
              instance_size = "M10"
            } : null
            read_only_specs = region.read_only_nodes > 0 ? {
              node_count    = region.read_only_nodes
              instance_size = "M10"
            } : null
          } if region.priority == priority
        ]
      ])
    }
  ]

  # Generated by atlas-cli-plugin-terraform.
  # Please review the changes and confirm that references to this resource are updated.
}

# example of variable for demostration purposes, not used in the conversion
variable "replication_specs" {
  type = object({
    num_shards = number
    regions_config = set(object({
      region_name     = string
      electable_nodes = number
      priority        = number
      read_only_nodes = number
    }))
  })
  default = {
    num_shards = 3
    regions_config = [
      {
        region_name     = "US_EAST_1"
        electable_nodes = 3
        priority        = 7
        read_only_nodes = 0
      },
      {
        region_name     = "US_WEST_2"
        electable_nodes = 2
        priority        = 6
        read_only_nodes = 1
      }
    ]
  }
}
