resource "mongodbatlas_advanced_cluster" "cluster1" {
  project_id   = var.project_id
  name         = "clu1"
  cluster_type = "REPLICASET"
  replication_specs = [
    {
      region_configs = [
        {
          provider_name = "AWS"
          region_name   = "US_EAST_1"
          priority      = 7
          electable_specs = {
            node_count    = 3
            instance_size = "M10"
          }
        }
      ]
    }
  ]

  # Generated by atlas-cli-plugin-terraform.
  # Please confirm that all references to this resource are updated.
}

resource "mongodbatlas_advanced_cluster" "cluster2" {
  project_id   = var.project_id
  name         = "clu2"
  cluster_type = "REPLICASET"
  replication_specs = [
    {
      region_configs = [
        {
          provider_name = "AWS"
          region_name   = "US_WEST_2"
          priority      = 7
          electable_specs = {
            node_count    = 3
            instance_size = "M30"
          }
        }
      ]
    }
  ]

  # Generated by atlas-cli-plugin-terraform.
  # Please confirm that all references to this resource are updated.
}

resource "mongodbatlas_advanced_cluster" "count" {
  # count doesn't affect moved blocks, it works in the same way
  count        = local.create_cluster ? 1 : 0
  project_id   = var.project_id
  name         = "count"
  cluster_type = "REPLICASET"
  replication_specs = [
    {
      region_configs = [
        {
          provider_name = "AWS"
          region_name   = "US_WEST_2"
          priority      = 7
          electable_specs = {
            node_count    = 3
            instance_size = "M30"
          }
        }
      ]
    }
  ]

  # Generated by atlas-cli-plugin-terraform.
  # Please confirm that all references to this resource are updated.
}

resource "mongodbatlas_advanced_cluster" "forEach" {
  # for_each doesn't affect moved blocks, it works in the same way
  for_each     = toset(["clu1", "clu2", "clu3"])
  project_id   = var.project_id
  name         = each.key
  cluster_type = "REPLICASET"
  replication_specs = [
    {
      region_configs = [
        {
          provider_name = "AWS"
          region_name   = "US_WEST_2"
          priority      = 7
          electable_specs = {
            node_count    = 3
            instance_size = "M30"
          }
        }
      ]
    }
  ]

  # Generated by atlas-cli-plugin-terraform.
  # Please confirm that all references to this resource are updated.
}

resource "another_resource" "another" {
  hello = "there"
}

# Moved blocks

moved {
  from = mongodbatlas_cluster.cluster1
  to   = mongodbatlas_advanced_cluster.cluster1
}

moved {
  from = mongodbatlas_cluster.cluster2
  to   = mongodbatlas_advanced_cluster.cluster2
}

moved {
  from = mongodbatlas_cluster.count
  to   = mongodbatlas_advanced_cluster.count
}

moved {
  from = mongodbatlas_cluster.forEach
  to   = mongodbatlas_advanced_cluster.forEach
}
