resource "mongodbatlas_advanced_cluster" "multi_region" {
  project_id   = "1234"
  name         = "cluster-multi-region"
  cluster_type = "REPLICASET"


  backup_enabled = true
  replication_specs = [{
    num_shards = 1
    region_configs = [{
      region_name   = "US_EAST_1"
      priority      = 7
      provider_name = "AWS"
      electable_specs = {
        node_count      = 3
        instance_size   = "M10"
        disk_size_gb   = 100
      }

      }, {
      region_name   = "US_WEST_2"
      priority      = 6
      provider_name = "AWS"
      electable_specs = {
        node_count      = 3
        instance_size   = "M10"
        disk_size_gb   = 100
      }
      }, {
      region_name   = "US_WEST_1"
      priority      = 5
      provider_name = "AWS"
      electable_specs = {
        node_count    = 1
        instance_size = "M10"
        disk_size_gb  = 100
      }
    }]
  }]

  # Generated by atlas-cli-plugin-terraform.
  # Please confirm that all references to this resource are updated.
}
