resource "mongodbatlas_advanced_cluster" "multirep" {
  project_id     = var.project_id
  name           = "multirep"
  backup_enabled = false
  cluster_type   = "GEOSHARDED"
  replication_specs = [
    {
      zone_name = "Zone 1"
      region_configs = [
        {
          region_name   = "US_EAST_1"
          priority      = 7
          provider_name = "AWS"
          electable_specs = {
            node_count    = 3
            instance_size = "M10"
            disk_size_gb  = 80
          }
        }
      ]
    },
    {
      zone_name = "Zone 2",
      region_configs = [
        {
          region_name   = "US_WEST_2"
          priority      = 7
          provider_name = "AWS"
          electable_specs = {
            node_count    = 3
            instance_size = "M10"
            disk_size_gb  = 80
          }
        }
      ]
    }
  ]

  # Generated by atlas-cli-plugin-terraform.
  # Please confirm that all references to this resource are updated.
}
