resource "mongodbatlas_advanced_cluster" "basictags" {
  project_id   = var.project_id
  name         = "basictags"
  cluster_type = "REPLICASET"
  replication_specs = [{
    region_configs = [{
      provider_name = "AWS"
      region_name   = "US_EAST_1"
      priority      = 7
      electable_specs = {
        node_count    = 3
        instance_size = "M10"
      }
    }]
  }]
  tags = {
    environment = "dev"
  }

  # Generated by atlas-cli-plugin-terraform.
  # Please confirm that all references to this resource are updated.
}

resource "mongodbatlas_advanced_cluster" "basictimeouts" {
  project_id   = var.project_id
  name         = "basictimeouts"
  cluster_type = "REPLICASET"
  replication_specs = [{
    region_configs = [{
      provider_name = "AWS"
      region_name   = "US_EAST_1"
      priority      = 7
      electable_specs = {
        node_count    = 3
        instance_size = "M10"
      }
    }]
  }]
  timeouts = {

    create = "60m"
  }

  # Generated by atlas-cli-plugin-terraform.
  # Please confirm that all references to this resource are updated.
}
