package convert

const (
	nRepSpecs                   = "replication_specs"
	nConfig                     = "region_configs"
	nConfigSrc                  = "regions_config"
	nElectableSpecs             = "electable_specs"
	nAutoScaling                = "auto_scaling"
	nReadOnlySpecs              = "read_only_specs"
	nAnalyticsSpecs             = "analytics_specs"
	nRegionNameSrc              = "provider_region_name"
	nRegionName                 = "region_name"
	nProviderName               = "provider_name"
	nBackingProviderName        = "backing_provider_name"
	nInstanceSizeSrc            = "provider_instance_size_name"
	nInstanceSize               = "instance_size"
	nClusterType                = "cluster_type"
	nPriority                   = "priority"
	nNumShards                  = "num_shards"
	nBackupEnabled              = "backup_enabled"
	nCloudBackup                = "cloud_backup"
	nDiskSizeGB                 = "disk_size_gb"
	nDiskGBEnabledSrc           = "auto_scaling_disk_gb_enabled"
	nComputeEnabledSrc          = "auto_scaling_compute_enabled"
	nComputeScaleDownEnabledSrc = "auto_scaling_compute_scale_down_enabled"
	nComputeMinInstanceSizeSrc  = "provider_auto_scaling_compute_min_instance_size"
	nComputeMaxInstanceSizeSrc  = "provider_auto_scaling_compute_max_instance_size"
	nEBSVolumeTypeSrc           = "provider_volume_type"
	nDiskIOPSSrc                = "provider_disk_iops"
	nDiskGBEnabled              = "disk_gb_enabled"
	nComputeEnabled             = "compute_enabled"
	nComputeScaleDownEnabled    = "compute_scale_down_enabled"
	nComputeMinInstanceSize     = "compute_min_instance_size"
	nComputeMaxInstanceSize     = "compute_max_instance_size"
	nEBSVolumeType              = "ebs_volume_type"
	nDiskIOPS                   = "disk_iops"
	nNodeCount                  = "node_count"
	nElectableNodes             = "electable_nodes"
	nReadOnlyNodes              = "read_only_nodes"
	nAnalyticsNodes             = "analytics_nodes"
)
